# Generated by Django 4.2 on 2023-07-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('stream', models.CharField(choices=[('science', 'Science'), ('commerce', 'Commerce'), ('arts', 'Arts')], max_length=10)),
                ('fees', models.BooleanField(default=True)),
            ],
        ),
    ]
