# Generated by Django 4.2 on 2023-07-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='fees',
            new_name='fees_paid',
        ),
        migrations.RenameField(
            model_name='studentmodel',
            old_name='rollno',
            new_name='roll_no',
        ),
    ]
