# Generated by Django 4.2 on 2023-07-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_studentmodel_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='roll_no',
            field=models.CharField(max_length=5),
        ),
    ]
